# Generated by Django 3.0.7 on 2020-09-20 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='loan_balance',
            field=models.IntegerField(null=True, verbose_name='Loan Balance'),
        ),
        migrations.AlterField(
            model_name='loans',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closed_by', to='staff.Staff'),
        ),
        migrations.AlterField(
            model_name='loans',
            name='loan_amount',
            field=models.IntegerField(null=True, verbose_name='Loan Amount'),
        ),
    ]
