# Generated by Django 3.0.7 on 2020-08-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20200819_2127'),
        ('app', '0002_auto_20200814_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
